# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Zerui Wang
tagline:          'Start here, make a difference.'
description:      'Forging Accessibility in Robotic Surgery'
url:              http://www.wangzerui.com/

author:
  name:           'Zerui Wang'
  email:          zerui.j.wang@gmail.com

paginate:         3
paginate_path: "blog/page:num"

gems: [jekyll-paginate]

# custom vars
since:                  2015
google_analytics:       UA-63207330-1
emailme:                mailto:zerui.j.wang@gmail.com
github:
  repo:                 https://github.com/zrwang/zrwang.github.io/
version:                Feb.2025 by OpenClaw
orcid_username:         0000-0003-4281-5120
researcherid_username:  R-3094-2018
googlescholar_username: fWi5tx8AAAAJ&hl
researchgate_username:  Zerui_Wang
linkedin_username:      zrwang
github_username:        zrwang
share_pdf:              no
share_video:            no
