# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Zerui Wang
tagline:          'Happy coding, happy blogging.'
description:      'Start here,<br>make a difference.'
url:              http://www.wangzerui.com/

author:
  name:           'Zerui Wang'
  email:          zerui.j.wang@gmail.com

paginate:         3
paginate_path: "blog/page:num"

gems: [jekyll-paginate]

# custom vars
since:                  2015
google_analytics:       UA-63207330-1
emailme:                mailto:zerui.j.wang@gmail.com
github:
  repo:                 https://github.com/zrwang/zrwang.github.io/
version:                May.18.2019
orcid_username:         0000-0003-4281-5120
researcherid_username:  R-3094-2018
googlescholar_username: fWi5tx8AAAAJ&hl
researchgate_username:  Zerui_Wang
linkedin_username:      zrwang
github_username:        zrwang
# facebook_username: zrwang.cuhk
# google_plus_username: 115306810481973645007
# twitter_username: wangzerui
# instagram_username: wzr.mavericker
# share_pdf: yes
# cv_chn: yes