# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Zerui Wang
tagline:          'Happy coding, happy blogging.'
description:      'Start here,<br>make a difference.'
url:              http://www.wangzerui.com/

author:
  name:           'Zerui Wang'
  email:          zerui.j.wang@gmail.com

paginate:         3
paginate_path: "blog/page:num"

gems: [jekyll-paginate]

# custom vars
google_analytics: UA-63207330-1
emailme:          mailto:zerui.j.wang@gmail.com
github:
  repo:           https://github.com/zrwang/zrwang.github.io/
version:          March.1.2018
github_username:  zrwang
facebook_username: zrwang.cuhk
linkedin_username: zrwang
twitter_username: wangzerui
orcid_username: 0000-0003-4281-5120
researchgate_username: Zerui_Wang
# share_pdf: yes
# google_plus_username:
# instagram_username: wzr.mavericker
