# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Zerui Wang
tagline:          'Happy coding, happy blogging.'
description:      'Start here,<br>make a difference.'
url:              http://www.wangzerui.com
baseurl:          /

author:
  name:           'Zerui Wang'
  email:          zerui.j.wang@gmail.com

paginate:         2

gems: [jekyll-paginate]

# custom vars
google_analytics: UA-63207330-1
emailme:          mailto:zerui.j.wang@gmail.com
github:
  repo:           https://github.com/zrwang/zrwang.github.io/
version:          Feb.21.2017
github_username:  zrwang
facebook_username: zrwang.cuhk
linkedin_username: zrwang
twitter_username: wangzerui
# google_plus_username: 
# instagram_username: wzr.mavericker

